name: Build
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
  workflow_call:
    inputs:
      stable-version:
        description: 'Build as a stable version (no prerelease suffix)'
        type: boolean
        required: false
        default: false

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases/tag/v6.0.1
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      # https://github.com/actions/setup-dotnet/releases/tag/v5.0.1
      - uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602
        name: Install .NET
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore

      - name: Build and pack
        run: dotnet pack --no-restore -p:StableVersion=${{ inputs.stable-version }} --output packages

      - name: Run tests
        run: dotnet test --no-restore --logger trx --results-directory test-results

      # https://github.com/actions/upload-artifact/releases/tag/v6.0.0
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        name: Upload NuGet packages
        with:
          name: nuget-packages
          path: packages/*.nupkg

      # https://github.com/actions/upload-artifact/releases/tag/v6.0.0
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        name: Upload test results
        # Ensures that test results are uploaded even if tests fail
        if: always()
        with:
          name: test-results
          path: test-results/*.trx
