name: Build
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:

jobs:
  build-and-pack:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases/tag/v6.0.1
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      # https://github.com/actions/setup-dotnet/releases/tag/v5.0.1
      - uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602
        name: Install .NET
        with:
          dotnet-version: 10.0.x

      - name: Build and pack
        run: dotnet pack
